spring:
    profiles: prod
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        platform: mysql
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
    session:
        store-type: none
server:
      port: 8080
mybatis:
    mapper-locations: classpath:*Mapper.xml
    type-aliases-package: com.example.been
    config-location: classpath:mybatis-config.xml
